### PR TITLE
Fixed an issue where rotating elements were too large

### PR DESCRIPTION
**Pull request by Taikono-Himazin**

### CODE REVIEW

**Comment by Taikono-Himazin** [comment]
sorry.
I made a mistake.

**Comment by Taikono-Himazin** [comment]
@statefb
Are you the administrator?
This pull request may contain confidential information, so could you please delete it?
You can request deletion by contacting support below.
https://support.github.com/contact?flow=pr_removal&subject=Delete%20Pull%20Request&tags=rr-remove-data
I apologize for any inconvenience caused by my mistake.

**Comment by statefb** [comment]
I asked the chatbot and he said created ticket to remove this PR. Please wait to be removed.

**Comment by Taikono-Himazin** [comment]
Oh, thank you very much.
It was helpful.

**Pull request closed without merging**
