### PR TITLE
Disable Aurora Disk encryption configuration

### PR DESCRIPTION
**Pull request by statefb**
*Issue #, if available:*

*Description of changes:*
- Changing storage encryitpion setting causes replacement

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by Taikono-Himazin** [comment]
Why did you remove the DB encryption settings?
I think this item is necessary.
Even if the RDS instance is recreated and the data is lost, it is only the VectorStore information, so the information will be recreated if you update the bot.

**Comment by statefb** [comment]
> recreated if you update the bot.

That's true, but imagine that app has 1000 or more bots, which is too many to update it. We'd like to decide carefully. But I agree with you that encryption must be implemented. Give us time to consider. Thank you

**Comment by Taikono-Himazin** [comment]
@statefb 
 If there is a change in DB Encryption (if aurora is recreated), wouldn't it be better to set the sync status of all bots in DynamoDB to queued?

**Comment by statefb** [comment]
@Taikono-Himazin I believe that we don't need to add any change to existing DDB items.  
If a more detailed discussion is needed, please feel free to contact me on [LinkedIn](in/takehiro-suzuki-430447203) and I will invite you to a dedicated chat room.

**Pull request merged**
