### PR TITLE
[WIP] Feature/claude 3

### PR DESCRIPTION
**Pull request by statefb**
*Issue #, if available:*
#125 

*Description of changes:*
- Add claude v3 sonnet option
- Multi modal input including text and image

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by rexsilex** [comment]
This branch gives me the following console error when trying to chat with any of the versions of claude including the new 3.

image

**Comment by Taikono-Himazin** [comment]
Thanks for the quick development!
I'm really looking forward to the release of this feature.


I tried the current pull request(b26b602e8787d45012dc89e0175e9e1feee6b4c7), but I feel that RAG (Bot function) is not working properly. It seems that knowledge is not loaded.
Is it correct that the RAG function is not yet supported in Claude3?

I tried checking the return value of compose_args_for_anthropic_client in backend/bedrock.py using breakpoints, etc., but it didn't seem to be searched for knowledge if it was local, so I couldn't understand it.

**Comment by statefb** [comment]
@rexsilex @Taikono-Himazin 
This feature is work in progress. Please wait until merged into main branch, thank you!

**Comment by Taikono-Himazin** [comment]
I'm sorry for making noise from the side.

I look forward to seeing this merged!

**Comment by Taikono-Himazin** [comment]
Thanks for your quick work!

**Pull request merged**
