### PR TITLE
feat(language): add french language to app

### PR DESCRIPTION
**Pull request by jeremylatorre**
*Description of changes:*
Adding language FR to the chatbot Interface

### CODE REVIEW

**Comment by statefb** [comment]
Duplicated #149

**Comment by statefb** [comment]
Could you fix root README.md like following?
```md
## 📚 Supported Languages

- English 💬
- 日本語 💬 (ドキュメントは[こちら](./docs/README_ja.md))
- 한국어 💬
- 中文 💬
- Français 💬
```

**Comment by jeremylatorre** [comment]
Update done

**Comment by statefb** [comment]
LGTM! Thank you for your contribution!

**Pull request merged**
