### PR TITLE
update chinese language to app

### PR DESCRIPTION
**Pull request by dennischang**
Add/update Chinese (simplified & traditional) files to i18n framework

### CODE REVIEW

**Review by wadabee — APPROVED** [review]
Thanks for your contribution!

**Review by wadabee — CHANGES_REQUESTED** [review]
getting a build error, so please fix it.
Please add the language you added to resources.

**Comment by dennischang** [comment]
Added! Thank you!

**Comment by statefb** [comment]
LGTM, thanks for contribution!

**Pull request merged**
